export default interface LessonWordModel {
    CardId: number,
    NoteId: number,
    AudioFileName: string,
    Context: string,
    ContextTranslation: string,
    DateCreated: Date,
    IPA: string,
    Lemma: string,
    ImageFileName: string,
    Word: string,
    WordDefinition: string,
    VideoTitle: string | null,
    Status: number,
    Checked: boolean,
    Updated: boolean,
    Tags: string[],
}